name: showcasing_flutter

description: Showcasing Flutter awesomeness. Purely for teaching & learning
  purpose. Flutter/Dart Tips & Tricks.

publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.7
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_dynamic_links: ^4.0.5
  provider: ^6.0.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
